<?xml version="1.0" encoding="UTF-8"?><testrun name="ScanNetNBTest" project="Prattle" tests="2" started="2" failures="1" errors="0" ignored="0">
  <testsuite name="edu.northeastern.ccs.im.ScanNetNBTest" time="0.21" displayname="ScanNetNBTest" uniqueid="[engine:junit-jupiter]/[class:edu.northeastern.ccs.im.ScanNetNBTest]">
    <testcase name="IOExceptionTest" classname="edu.northeastern.ccs.im.ScanNetNBTest" time="0.187" displayname="IOExceptionTest()" uniqueid="[engine:junit-jupiter]/[class:edu.northeastern.ccs.im.ScanNetNBTest]/[method:IOExceptionTest()]">
      <failure>org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==&gt; expected: &lt;java.io.IOException&gt; but was: &lt;java.lang.NullPointerException&gt;&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:59)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:38)&#13;
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:1108)&#13;
	at edu.northeastern.ccs.im.ScanNetNBTest.IOExceptionTest(ScanNetNBTest.java:47)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:389)&#13;
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)&#13;
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:167)&#13;
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)&#13;
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:163)&#13;
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:110)&#13;
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)&#13;
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)&#13;
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)&#13;
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)&#13;
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)&#13;
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)&#13;
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)&#13;
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)&#13;
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)&#13;
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)&#13;
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)&#13;
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)&#13;
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)&#13;
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)&#13;
Caused by: java.lang.NullPointerException&#13;
	at edu.northeastern.ccs.im.ScanNetNB.&lt;init&gt;(ScanNetNB.java:72)&#13;
	at edu.northeastern.ccs.im.ScanNetNBTest.lambda$0(ScanNetNBTest.java:48)&#13;
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:50)&#13;
	... 56 more&#13;
&#13;
</failure>
    </testcase>
    <testcase name="hasNextFail" classname="edu.northeastern.ccs.im.ScanNetNBTest" time="0.023" displayname="hasNextFail()" uniqueid="[engine:junit-jupiter]/[class:edu.northeastern.ccs.im.ScanNetNBTest]/[method:hasNextFail()]"/>
  </testsuite>
</testrun>
